const motivationalQuotes: string[] = [
  "Believe you can and you're halfway there.",
  "The only way to do great work is to love what you do.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Don't watch the clock; do what it does. Keep going.",
  "You are never too old to set another goal or to dream a new dream.",
  "If you want to achieve greatness stop asking for permission.",
  "Your limitation—it's only your imagination.",
  "Push yourself, because no one else is going to do it for you.",
  "Sometimes later becomes never. Do it now.",
  "Great things never come from comfort zones.",
  "Dream it. Wish it. Do it.",
  "Success doesn’t just find you. You have to go out and get it.",
  "The harder you work for something, the greater you’ll feel when you achieve it.",
  "Dream bigger. Do bigger.",
  "Don’t stop when you’re tired. Stop when you’re done.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Do something today that your future self will thank you for.",
  "Little things make big days.",
  "It’s going to be hard, but hard does not mean impossible.",
  "Don’t wait for opportunity. Create it.",
  "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
  "The key to success is to focus on goals, not obstacles.",
  "Dream it. Believe it. Build it.",
  "Start where you are. Use what you have. Do what you can.",
  "Don’t downgrade your dream just to fit your reality, upgrade your conviction to match your destiny.",
  "Work hard in silence, let your success be your noise.",
  "Don’t stop until you’re proud.",
  "We generate fears while we sit. We overcome them by action.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Do what you can with all you have, wherever you are.",
  "It always seems impossible until it’s done.",
  "Good things come to those who hustle.",
  "The way to get started is to quit talking and begin doing.",
  "You don’t have to be great to start, but you have to start to be great.",
  "The secret of getting ahead is getting started.",
  "Success is not how high you have climbed, but how you make a positive difference to the world.",
  "In the middle of every difficulty lies opportunity.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "The only place where success comes before work is in the dictionary.",
  "Challenges are what make life interesting and overcoming them is what makes life meaningful.",
  "Don't let yesterday take up too much of today.",
  "Act as if what you do makes a difference. It does.",
  "You have to expect things of yourself before you can do them.",
  "Go the extra mile. It’s never crowded there.",
  "The difference between ordinary and extraordinary is that little extra.",
  "Success usually comes to those who are too busy to be looking for it.",
  "Don’t be afraid to give up the good to go for the great.",
  "I find that the harder I work, the more luck I seem to have.",
];

export default motivationalQuotes;
